### ISSUE TITLE
Use temporary security credentials with AWS CLI

### ISSUE THREAD

**Issue by wkzqn** [aws/rolesanywhere-credential-helper#28]
This is config file:
```
[default]
region = us-east-1
credential_process = ./aws_signing_helper.exe credential-process --certificate ./client/client-01.crt --private-key ./client/client-01.key --profile-arn xxxx --role-arn xxxx --trust-anchor-arn xxxx --no-verify-ssl --with-proxy --debug --region us-east-1
```
It prompts json to parse exceptions. I don't know where json was parsed.,

**Comment by wkzqn** [comment]
The following is the error message:
```
aws sts get-caller-identity --no-verify-ssl --debug
2023-03-01 16:25:25,020 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.9.14 Python/3.9.11 Windows/10 exe/AMD64
2023-03-01 16:25:25,021 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sts', 'get-caller-identity', '--no-verify-ssl', '--debug']
2023-03-01 16:25:25,094 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x000001CEB3FDECA0>
2023-03-01 16:25:25,094 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x000001CEB3E35430>
2023-03-01 16:25:25,095 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2023-03-01 16:25:25,096 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x000001CEB3DC8430>
2023-03-01 16:25:25,096 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x000001CEB3DCF430>
2023-03-01 16:25:25,096 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x000001CEB3FEE670>
2023-03-01 16:25:25,096 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x000001CEB3E7EF70>
2023-03-01 16:25:25,096 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2023-03-01 16:25:25,096 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x000001CEB3FA58B0>
2023-03-01 16:25:25,096 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x000001CEB40970A0>>
2023-03-01 16:25:25,096 - MainThread - botocore.loaders - DEBUG - Loading JSON file: D:\Programs\AWSCLIV2\awscli\data\cli.json
2023-03-01 16:25:25,099 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x000001CEB3F309D0>
2023-03-01 16:25:25,099 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x000001CEB3F33550>
2023-03-01 16:25:25,099 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x000001CEB3F334C0>
2023-03-01 16:25:25,099 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x000001CEB3F33670>
2023-03-01 16:25:25,099 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x000001CEB3F335E0>
2023-03-01 16:25:25,099 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x000001CEB408DB80>
2023-03-01 16:25:25,100 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.9.14 Python/3.9.11 Windows/10 exe/AMD64 prompt/off
2023-03-01 16:25:25,100 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sts', 'get-caller-identity', '--no-verify-ssl', '--debug']
2023-03-01 16:25:25,100 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x000001CEB3FE0310>
2023-03-01 16:25:25,100 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x000001CEB3348DC0>
2023-03-01 16:25:25,100 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x000001CEB4043790>
2023-03-01 16:25:25,101 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x000001CEB3346160>
2023-03-01 16:25:25,101 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x000001CEB3BABA60>
2023-03-01 16:25:25,105 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2023-03-01 16:25:25,106 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x000001CEB3E7EE50>
2023-03-01 16:25:25,106 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x000001CEB3E2A1F0>
2023-03-01 16:25:25,178 - MainThread - botocore.loaders - DEBUG - Loading JSON file: D:\Programs\AWSCLIV2\awscli\botocore\data\sts\2011-06-15\service-2.json
2023-03-01 16:25:25,180 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sts: calling handler <function add_waiters at 0x000001CEB3FA58B0>
2023-03-01 16:25:25,253 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sts: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x000001CEB40970A0>>
2023-03-01 16:25:25,256 - MainThread - awscli.clidriver - DEBUG - OrderedDict()
2023-03-01 16:25:25,256 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_streaming_output_arg at 0x000001CEB3FE05E0>
2023-03-01 16:25:25,256 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_cli_input_json at 0x000001CEB3BAE280>
2023-03-01 16:25:25,256 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_cli_input_yaml at 0x000001CEB3BAE4C0>
2023-03-01 16:25:25,256 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function unify_paging_params at 0x000001CEB3E359D0>
2023-03-01 16:25:25,328 - MainThread - botocore.loaders - DEBUG - Loading JSON file: D:\Programs\AWSCLIV2\awscli\botocore\data\sts\2011-06-15\paginators-1.json
2023-03-01 16:25:25,329 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_generate_skeleton at 0x000001CEB3F22F70>
2023-03-01 16:25:25,330 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x000001CEB40EE9D0>>
2023-03-01 16:25:25,330 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x000001CEB40EEA00>>
2023-03-01 16:25:25,331 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x000001CEB40EE8B0>>
2023-03-01 16:25:25,331 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sts_get-caller-identity: calling handler <function add_waiters at 0x000001CEB3FA58B0>
2023-03-01 16:25:25,331 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sts_get-caller-identity: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x000001CEB40970A0>>
2023-03-01 16:25:25,332 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001CEB40DD880>
2023-03-01 16:25:25,332 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001CEB40DD880>
2023-03-01 16:25:25,332 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001CEB40DD880>
2023-03-01 16:25:25,332 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x000001CEB40EE9D0>>
2023-03-01 16:25:25,332 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x000001CEB40EEA00>>
2023-03-01 16:25:25,332 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x000001CEB40EE8B0>>
2023-03-01 16:25:25,333 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2023-03-01 16:25:25,333 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2023-03-01 16:25:25,333 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2023-03-01 16:25:25,333 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2023-03-01 16:25:25,333 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2023-03-01 16:25:25,333 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: custom-process
2023-03-01 16:25:26,595 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli\clidriver.py", line 460, in main
  File "awscli\clidriver.py", line 595, in __call__
  File "awscli\clidriver.py", line 798, in __call__
  File "awscli\clidriver.py", line 925, in invoke
  File "awscli\botocore\session.py", line 838, in create_client
  File "awscli\botocore\session.py", line 443, in get_credentials
  File "awscli\botocore\credentials.py", line 1939, in load_credentials
  File "awscli\botocore\credentials.py", line 924, in load
  File "awscli\botocore\credentials.py", line 951, in _retrieve_credentials_using
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

Extra data: line 1 column 5 (char 4)
```

**Comment by wkzqn** [comment]
The reason is found. -- debug cannot be added to the config file.
